version: '2'

services:
   db:
     image: mysql:8
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     volumes:
       - db_data_8:/var/lib/mysql
     restart: always
     ports:
       - "3326:3306"
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: tomcat_db  
       MYSQL_USER: tomcat_user
       MYSQL_PASSWORD: 1234 

   tomcat_8.5:
     depends_on:
       - db
     image: tomcat:8.5 
     restart: always
     volumes:
       - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
       - ./manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml  
     ports:
       - "9080:8080"
     restart: always

volumes:
    db_data_8:
